# Site settings
author: Mariel Hoepelman
title: Mariel Hoepelman
header-img: img/home-bg.png
email: marielhoepelman@gmail.com
copyright_name: Mariel Hoepelman
description: > # this means to ignore newlines until "baseurl:"
  coder wannabe
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MarielJHoepelman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
